package(
    default_visibility = [
        "//visibility:public",
    ],
)

cc_test(
    name = "two_sum",
    srcs = ["two_sum.cc"],
    deps = [
        "//src/base/test:test_main",
    ]
)

cc_test(
    name = "add_two_numbers",
    srcs = ["add_two_numbers.cc"],
    deps = [
        "//src/base/test:test_main",
    ]
)

cc_test(
    name = "longest_substring_without_repeating_characters",
    srcs = ["longest_substring_without_repeating_characters.cc"],
    deps = [
        "//src/base/test:test_main",
        "@com_google_glog//:glog",
    ]
)
