package(
    default_visibility = [
        "//visibility:public",
    ],
)

cc_test(
    name = "two_sum",
    srcs = ["two_sum.cc"],
    deps = [
        "//src/base/test:test_main",
    ]
)


cc_test(
    name = "add_two_numbers",
    srcs = ["add_two_numbers.cc"],
    deps = [
        "//src/base/test:test_main",
    ]
)