package(
    default_visibility = [
        "//visibility:public",
    ],
)

cc_library(
    name = "test_main",
    testonly = 1,
    srcs = ["test_main.cc"],
    deps = [
        "@com_google_glog//:glog",
        "@com_google_googletest//:gtest",
    ],
)
