package(
    default_visibility = [
        "//visibility:public",
    ],
)

cc_library(
    name = "logging",
    srcs = ["logging.cc"],
    hdrs = ["logging.h"],
    deps = [
        "@com_google_absl//absl/strings",
        "@com_google_glog//:glog",
        "@com_google_absl//absl/time",
    ],
)


